"""Generate C stub headers from ARXML software components / interfaces."""

from __future__ import annotations

from pathlib import Path

from auto_validator.models.arxml_models import ArxmlModel, ArxmlSoftwareComponent, PortDirection
from auto_validator.utils.logging import get_logger

logger = get_logger("codegen.c_stubs")

_TYPE_MAP = {
    "boolean": "boolean",
    "bool": "boolean",
    "uint8": "uint8",
    "uint16": "uint16",
    "uint32": "uint32",
    "uint64": "uint64",
    "sint8": "sint8",
    "sint16": "sint16",
    "sint32": "sint32",
    "sint64": "sint64",
    "float32": "float32",
    "float64": "float64",
}


def _c_type(data_type: str) -> str:
    return _TYPE_MAP.get(data_type.lower(), data_type)


def _guard(name: str) -> str:
    return f"Rte_{name}_H".upper().replace("-", "_")


class CStubGenerator:
    """Emit per-SWC RTE-style C stub headers."""

    def generate(self, model: ArxmlModel, output_dir: Path | str) -> list[Path]:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []

        for swc in model.components:
            path = output_dir / f"Rte_{swc.name}.h"
            path.write_text(self._render_swc(swc, model), encoding="utf-8")
            written.append(path)
            logger.info("Generated C stub: %s", path)

        # Shared types header
        types_path = output_dir / "Rte_Type.h"
        types_path.write_text(self._render_types(model), encoding="utf-8")
        written.append(types_path)
        return written

    def _render_types(self, model: ArxmlModel) -> str:
        lines = [
            "/**",
            " * @file Rte_Type.h",
            " * @brief Auto-generated RTE type stubs — DO NOT EDIT",
            " * Generated by auto-validator",
            " */",
            "#ifndef RTE_TYPE_H",
            "#define RTE_TYPE_H",
            "",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            "",
            "typedef uint8_t  uint8;",
            "typedef uint16_t uint16;",
            "typedef uint32_t uint32;",
            "typedef uint64_t uint64;",
            "typedef int8_t   sint8;",
            "typedef int16_t  sint16;",
            "typedef int32_t  sint32;",
            "typedef int64_t  sint64;",
            "typedef float    float32;",
            "typedef double   float64;",
            "typedef bool     boolean;",
            "typedef uint8    Std_ReturnType;",
            "",
            "#ifndef E_OK",
            "#define E_OK     ((Std_ReturnType)0u)",
            "#define E_NOT_OK ((Std_ReturnType)1u)",
            "#endif",
            "",
        ]
        # Application types referenced but not primitive
        custom = sorted(
            {
                de.data_type
                for iface in model.interfaces
                for de in iface.data_elements
                if de.data_type.lower() not in _TYPE_MAP
            }
        )
        for ctype in custom:
            lines.append(f"typedef uint32 {ctype}; /* application type stub */")
        if custom:
            lines.append("")
        lines.extend(["#endif /* RTE_TYPE_H */", ""])
        return "\n".join(lines)

    def _render_swc(self, swc: ArxmlSoftwareComponent, model: ArxmlModel) -> str:
        guard = _guard(swc.name)
        lines = [
            "/**",
            f" * @file Rte_{swc.name}.h",
            f" * @brief Auto-generated RTE stubs for SWC '{swc.name}' — DO NOT EDIT",
            " */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            '#include "Rte_Type.h"',
            "",
            "#ifdef __cplusplus",
            'extern "C" {',
            "#endif",
            "",
        ]

        for port in swc.ports:
            iface = model.interface_by_name(port.interface_name) or model.interface_by_ref(
                port.interface_ref
            )
            if iface is None:
                lines.append(f"/* WARNING: unresolved interface for port {port.name} */")
                continue

            if iface.interface_type == "sender-receiver":
                for de in iface.data_elements:
                    ctype = _c_type(de.data_type)
                    if port.direction in (PortDirection.PROVIDED, PortDirection.PROVIDED_REQUIRED):
                        lines.append(
                            f"Std_ReturnType Rte_Write_{port.name}_{de.name}({ctype} data);"
                        )
                    if port.direction in (PortDirection.REQUIRED, PortDirection.PROVIDED_REQUIRED):
                        lines.append(
                            f"Std_ReturnType Rte_Read_{port.name}_{de.name}({ctype} *data);"
                        )
            elif iface.interface_type == "client-server":
                for op in iface.operations:
                    args = []
                    for arg in op.arguments:
                        at = _c_type(arg.data_type)
                        if arg.direction.upper() in {"OUT", "INOUT"}:
                            args.append(f"{at} *{arg.name}")
                        else:
                            args.append(f"{at} {arg.name}")
                    arglist = ", ".join(args) if args else "void"
                    prefix = "Call" if port.direction == PortDirection.REQUIRED else "Entry"
                    lines.append(
                        f"Std_ReturnType Rte_{prefix}_{port.name}_{op.name}({arglist});"
                    )

            lines.append("")

        lines.extend(
            [
                "#ifdef __cplusplus",
                "}",
                "#endif",
                "",
                f"#endif /* {guard} */",
                "",
            ]
        )
        return "\n".join(lines)
